on:
  push:
    branches:
    - "issue/*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        readonly local last_commit_msg=$(git log -1 --pretty=format:"%s")
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "master"                      # If blank, default: master
        pr_title: "${{ last_commit_msg }}" # Title of pull request
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_draft: true                                    # Creates pull request as draft
        github_token: ${{ secrets.GITHUB_TOKEN }}
